default_stages: [ commit ]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: ['--line-length', '160']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.285
    hooks:
      - id: ruff
        args:
          - --fix

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        files: ^chatgit/|^tests/
        additional_dependencies:
          [ pydantic==1.10.8,
            types-toml==0.10.8.7,
            types-python-dateutil==2.8.9,
            types-requests==2.31.0.2,
            types-urllib3==1.26.25.14
          ]
