[tool.poetry]
name = "chatgit"
version = "0.1.0"
description = ""
authors = ["hezhaozhao <hezhaozhaog@gmail.com>"]
readme = "README.md"
packages = [{include = "chatgit"}]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
tenacity = "^8.2.3"
loguru = "^0.7.0"


[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple"
priority = "primary"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
