[tool.poetry]
name = "chatgit"
version = "0.1.0"
description = ""
authors = ["hezhaozhao <hezhaozhaog@gmail.com>"]
readme = "README.md"
packages = [{ include = "chatgit" }]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
tenacity = "^8.2.3"
loguru = "^0.7.0"
jsonlines = "^3.1.0"
ratelimit = "^2.2.1"
toml = "^0.10.2"
fastapi = "^0.101.1"
uvicorn = "^0.23.2"
pydantic = "1.10.8"
ormar = {extras = ["mysql", "orjson"], version = "^0.12.2"}
tomli = "^2.0.1"
httpx = "^0.24.1"
sqlalchemy = ">=1.3.18,<1.4.42"


[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple"
priority = "primary"


[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.poetry.group.dev.dependencies]
black = { extras = ["d"], version = "^23.7.0" }
mypy = "^1.5.1"
types-toml = "^0.10.8.7"
mypy-extensions = "^1.0.0"
types-requests = "2.31.0.2"
types-urllib3 = "1.26.25.14"
pre-commit = "^3.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
line-length = 160
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "I", # isort
    "C", # flake8-comprehensions
    "B", # flake8-bugbear
]
ignore = [
    "E501", # line too long, handled by black
    "B008", # do not perform function calls in argument defaults
    "C901", # too complex
]


[tool.black]
line-length = 160
target-version = ['py39', 'py310', 'py311']
#include = '\.pyi?$'
#extend-exclude = '''
#/(
#  # The following are specific to Black, you probably don't want those.
#  tests/data
#  | profiling
#)/
#'''
# We use preview style for formatting Black itself. If you
# want stable formatting across releases, you should keep
# this off.
preview = false

[tool.mypy]
plugins = ["pydantic.mypy"]

follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true

# for strict mypy: (this is the tricky one :-))
disallow_untyped_defs = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
